import '@/styles/globals.css';
import { Locale, i18n } from '@/i18n/i18n-config';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NavigationBar from '@/app/[lang]/components/navigation/NavigationBar';
import { Footer } from './components/footer/Footer';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({ children, params }: { children: React.ReactNode, params: { lang: Locale } }) {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
        <NavigationBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}